// src/components/ui/SwipeActionList.tsx
import { useRef, useState } from "react";
import "../../lib/kit-controls.css";
export interface SwipeItem {
  id: string;
  title: string;
  description?: string;
}
export interface SwipeActionListProps {
  items?: SwipeItem[];
  actionLabel?: string;
  onAction?: (item: SwipeItem) => void | Promise<void>;
  disabled?: boolean;
  loading?: boolean;
}
const samples: SwipeItem[] = [
  {
    id: "one",
    title: "Review the small details",
    description: "Design · Today",
  },
  {
    id: "two",
    title: "Ship something thoughtful",
    description: "Engineering · Tomorrow",
  },
];
function SwipeRow({
  item,
  actionLabel,
  onAction,
  disabled,
}: {
  item: SwipeItem;
  actionLabel: string;
  onAction: () => Promise<void>;
  disabled: boolean;
}) {
  const start = useRef<{ x: number; y: number } | null>(null);
  const [offset, setOffset] = useState(0);
  const [revealed, setRevealed] = useState(false);
  return (
    <li className="kit-surface kit-stack" style={{ overflow: "hidden" }}>
      <div
        className="kit-swipe"
        style={{ transform: `translateX(${offset}px)` }}
        onPointerDown={(e) => {
          if (disabled || e.button !== 0) return;
          start.current = { x: e.clientX, y: e.clientY };
        }}
        onPointerMove={(e) => {
          if (!start.current) return;
          if (Math.abs(e.clientY - start.current.y) > 35) {
            start.current = null;
            setOffset(0);
            return;
          }
          setOffset(Math.max(-96, Math.min(0, e.clientX - start.current.x)));
        }}
        onPointerUp={() => {
          setRevealed(offset < -40);
          start.current = null;
          setOffset(0);
        }}
        onPointerCancel={() => {
          start.current = null;
          setOffset(0);
        }}
        onPointerLeave={() => {
          start.current = null;
          setOffset(0);
        }}
      >
        <h3>{item.title}</h3>
        <p className="kit-muted">{item.description}</p>
      </div>
      <div className="kit-row">
        <button
          type="button"
          disabled={disabled}
          aria-expanded={revealed}
          onClick={() => setRevealed(!revealed)}
        >
          {revealed ? "Hide actions" : "Show actions"}
        </button>
        {revealed && (
          <button
            type="button"
            disabled={disabled}
            onClick={() => void onAction()}
          >
            {actionLabel} <span className="sr-only">{item.title}</span>
          </button>
        )}
      </div>
    </li>
  );
}
export function SwipeActionList({
  items = samples,
  actionLabel = "Archive",
  onAction,
  disabled = false,
  loading = false,
}: SwipeActionListProps) {
  const [done, setDone] = useState<string[]>([]);
  const [pending, setPending] = useState<string | null>(null);
  const [status, setStatus] = useState("");
  const busy = useRef(false);
  async function act(item: SwipeItem) {
    if (busy.current) return;
    busy.current = true;
    setPending(item.id);
    setStatus(`${actionLabel} in progress…`);
    try {
      await onAction?.(item);
      setDone((d) => [...d, item.id]);
      setStatus(`${item.title}: ${actionLabel.toLowerCase()} complete.`);
    } catch {
      setStatus("Action failed. Your item is unchanged; try again.");
    } finally {
      setPending(null);
      busy.current = false;
    }
  }
  const visible = items.filter((i) => !done.includes(i.id));
  return (
    <section
      className="kit-control kit-stack"
      aria-label="Swipe actions"
      aria-busy={loading || !!pending}
    >
      <p className="kit-muted">Swipe left or use Show actions.</p>
      {loading ? (
        <p>Loading items…</p>
      ) : (
        <ul className="kit-list">
          {visible.map((item) => (
            <SwipeRow
              key={item.id}
              item={item}
              actionLabel={pending === item.id ? "Working…" : actionLabel}
              onAction={() => act(item)}
              disabled={disabled || !!pending}
            />
          ))}
        </ul>
      )}
      {!loading && !visible.length && <p>All clear. No items to show.</p>}
      <p role="status" className="kit-status">
        {status}
      </p>
      {done.length > 0 && (
        <button
          type="button"
          disabled={disabled || !!pending}
          onClick={() => {
            setDone([]);
            setStatus("Items restored locally.");
          }}
        >
          Restore list
        </button>
      )}
    </section>
  );
}

// packages/angular/src/swipe-action-list.component.ts
import {
  Component,
  DestroyRef,
  computed,
  inject,
  input,
  signal,
} from "@angular/core";
import type { SwipeItem } from "./types";

@Component({
  selector: "kit-swipe-action-list",
  standalone: true,
  host: { style: "display:block" },
  template: ` <section
    class="kit-control kit-stack"
    aria-label="Swipe actions"
    [attr.aria-busy]="loading() || !!pending()"
  >
    <p class="kit-muted">Swipe left or use Show actions.</p>
    @if (loading()) {
      <p>Loading items…</p>
    } @else {
      <ul class="kit-list">
        @for (item of visible(); track item.id) {
          <li class="kit-surface kit-stack" style="overflow:hidden">
            <div
              class="kit-swipe"
              [style.transform]="
                'translateX(' + (dragId() === item.id ? offset() : 0) + 'px)'
              "
              (pointerdown)="start($event, item.id)"
              (pointermove)="move($event, item.id)"
              (pointerup)="end(item.id)"
              (pointercancel)="cancel()"
              (pointerleave)="cancel()"
            >
              <h3>{{ item.title }}</h3>
              <p class="kit-muted">{{ item.description }}</p>
            </div>
            <div class="kit-row">
              <button
                type="button"
                [disabled]="disabled() || !!pending()"
                [attr.aria-expanded]="revealed() === item.id"
                (click)="reveal(item.id)"
              >
                {{ revealed() === item.id ? "Hide actions" : "Show actions" }}
              </button>
              @if (revealed() === item.id) {
                <button
                  type="button"
                  [disabled]="disabled() || !!pending()"
                  (click)="act(item)"
                >
                  {{ pending() === item.id ? "Working…" : actionLabel() }}
                  <span class="sr-only">{{ item.title }}</span>
                </button>
              }
            </div>
          </li>
        }
      </ul>
      @if (!visible().length) {
        <p>All clear. No items to show.</p>
      }
    }
    <p role="status" class="kit-status">{{ status() }}</p>
    @if (done().length) {
      <button
        type="button"
        [disabled]="disabled() || !!pending()"
        (click)="restore()"
      >
        Restore list
      </button>
    }
  </section>`,
})
export class KitSwipeActionListComponent {
  readonly items = input<SwipeItem[]>([
    {
      id: "one",
      title: "Review the small details",
      description: "Design · Today",
    },
    {
      id: "two",
      title: "Ship something thoughtful",
      description: "Engineering · Tomorrow",
    },
  ]);
  readonly actionLabel = input("Archive");
  readonly action = input<(item: SwipeItem) => void | Promise<void>>();
  readonly disabled = input(false);
  readonly loading = input(false);
  readonly done = signal<string[]>([]);
  readonly pending = signal<string | null>(null);
  readonly status = signal("");
  readonly revealed = signal<string | null>(null);
  readonly dragId = signal<string | null>(null);
  readonly offset = signal(0);
  readonly visible = computed(() =>
    this.items().filter((i) => !this.done().includes(i.id)),
  );
  private origin: { x: number; y: number } | null = null;
  private destroyed = false;
  constructor() {
    inject(DestroyRef).onDestroy(() => {
      this.destroyed = true;
    });
  }
  reveal(id: string): void {
    this.revealed.set(this.revealed() === id ? null : id);
  }
  start(event: PointerEvent, id: string): void {
    if (this.disabled() || this.pending() || event.button !== 0) return;
    this.origin = { x: event.clientX, y: event.clientY };
    this.dragId.set(id);
  }
  move(event: PointerEvent, id: string): void {
    if (!this.origin || this.dragId() !== id) return;
    if (Math.abs(event.clientY - this.origin.y) > 35) {
      this.cancel();
      return;
    }
    this.offset.set(Math.max(-96, Math.min(0, event.clientX - this.origin.x)));
  }
  end(id: string): void {
    if (this.dragId() === id)
      this.revealed.set(this.offset() < -40 ? id : null);
    this.cancel();
  }
  cancel(): void {
    this.origin = null;
    this.dragId.set(null);
    this.offset.set(0);
  }
  restore(): void {
    this.done.set([]);
    this.status.set("Items restored locally.");
  }
  async act(item: SwipeItem): Promise<void> {
    if (this.pending() || this.disabled()) return;
    this.pending.set(item.id);
    this.status.set(`${this.actionLabel()} in progress…`);
    try {
      await this.action()?.(item);
      if (!this.destroyed) {
        this.done.update((items) => [...items, item.id]);
        this.status.set(`${item.title}: action complete.`);
      }
    } catch {
      if (!this.destroyed)
        this.status.set("Action failed. Your item is unchanged; try again.");
    } finally {
      if (!this.destroyed) this.pending.set(null);
    }
  }
}
