// packages/angular/src/ai-prompt-composer.component.ts
import { Component, DestroyRef, inject, input, signal } from "@angular/core";
import type { SendHandler } from "./types";

let nextComposerId = 0;

@Component({
  selector: "kittu-ai-prompt-composer",
  standalone: true,
  host: { style: "display:block" },
  template: ` <form
    class="kittu-control kittu-surface kittu-stack"
    aria-label="AI prompt composer"
    [attr.aria-busy]="pending()"
    (submit)="submit($event)"
  >
    <label [attr.for]="id">What are you thinking?</label>
    <textarea
        [id]="id"
        rows="4"
        maxlength="8000"
        [value]="text()"
        [disabled]="disabled() || pending()"
        (input)="edit($event)"
        (keydown)="keyDown($event)"
        placeholder="Start with a small idea…"
      ></textarea>
    <div class="kittu-row" aria-label="Prompt suggestions">
      @for (suggestion of suggestions(); track $index) {
        <button
          type="button"
          [disabled]="disabled() || pending()"
          (click)="text.set(suggestion)"
        >{{ suggestion }}</button>
      }
    </div>
    <label [attr.for]="id + '-files'">Attachments · up to {{ maxAttachments() }}</label>
    <input
        [id]="id + '-files'"
        type="file"
        multiple
        [disabled]="disabled() || pending()"
        (change)="attach($event)"
    />
    <ul class="kittu-list">
      @for (file of files(); track $index) {
        <li class="kittu-row">
          <span style="overflow-wrap:anywhere">{{ file.name }}</span
          ><button
            type="button"
            [disabled]="disabled() || pending()"
            (click)="remove($index)"
          >
            Remove <span class="sr-only">{{ file.name }}</span>
          </button>
        </li>
      }
    </ul>
    <div class="kittu-row">
      <span class="kittu-muted"
        >{{ text().length }}/8000 · ⌘ / Ctrl Enter to send</span
      ><button
        type="submit"
        [disabled]="disabled() || pending() || !text().trim() || !handler()"
      >{{ pending() ? "Sending…" : "Send prompt ↗" }}</button>
      @if (pending()) {
        <button type="button" (click)="cancel()">Cancel</button>
      }
    </div>
    <p role="status" class="kittu-status">
      {{
        status() ||
          (handler()
            ? "Your draft stays here until sending succeeds."
            : "Connect an onSend handler to send prompts.")
      }}
    </p>
  </form>`,
})
export class KittuAIPromptComposerComponent {
  readonly id = `kittu-prompt-${++nextComposerId}`;
  readonly suggestions = input<string[]>([
    "Explain this simply",
    "Help me find a direction",
    "Review my draft",
  ]);
  readonly onSend = input<SendHandler>();
  /** @deprecated Use onSend to match the React API. */
  readonly sendHandler = input<SendHandler>();
  handler(): SendHandler | undefined { return this.onSend() ?? this.sendHandler(); }
  readonly disabled = input(false);
  readonly maxAttachments = input(4);
  readonly maxAttachmentSize = input(10 * 1024 * 1024);
  readonly text = signal("");
  readonly files = signal<File[]>([]);
  readonly status = signal("");
  readonly pending = signal(false);
  private controller: AbortController | null = null;
  constructor() {
    inject(DestroyRef).onDestroy(() => {
      this.controller?.abort();
      this.controller = null;
    });
  }
  edit(event: Event): void {
    this.text.set((event.target as HTMLTextAreaElement).value);
  }
  remove(index: number): void {
    this.files.update((files) => files.filter((_, i) => i !== index));
  }
  attach(event: Event): void {
    const input = event.target as HTMLInputElement;
    const incoming = Array.from(input.files ?? []);
    if (
      this.files().length + incoming.length > this.maxAttachments() ||
      incoming.some((file) => file.size > this.maxAttachmentSize())
    )
      this.status.set(
        `Choose up to ${this.maxAttachments()} attachments, each under ${Math.round(this.maxAttachmentSize() / 1024 / 1024)} MB.`,
      );
    else {
      this.files.update((files) => [...files, ...incoming]);
      this.status.set("Attachments added.");
    }
    input.value = "";
  }
  submit(event: Event): void {
    event.preventDefault();
    void this.send();
  }
  keyDown(event: KeyboardEvent): void {
    if ((event.ctrlKey || event.metaKey) && event.key === "Enter") {
      event.preventDefault();
      void this.send();
    }
  }
  cancel(): void {
    this.controller?.abort();
    this.controller = null;
    this.pending.set(false);
    this.status.set("Sending cancelled. Your draft is saved.");
  }
  async send(): Promise<void> {
    const handler = this.handler();
    if (this.disabled() || this.controller || !this.text().trim() || !handler)
      return;
    const request = new AbortController();
    this.controller = request;
    this.pending.set(true);
    this.status.set("Sending…");
    try {
      await handler(
        { text: this.text().trim(), attachments: this.files() },
        request.signal,
      );
      if (!request.signal.aborted) {
        this.text.set("");
        this.files.set([]);
        this.status.set("Prompt sent.");
      }
    } catch {
      if (!request.signal.aborted)
        this.status.set("Sending failed. Your draft is saved; try again.");
    } finally {
      if (this.controller === request) {
        this.controller = null;
        this.pending.set(false);
      }
    }
  }
}

// src/components/ui/AIPromptComposer.tsx
import { useEffect, useId, useRef, useState } from "react";
import "../../lib/kittu-controls.css";
export interface PromptPayload {
  text: string;
  attachments: File[];
}
export interface AIPromptComposerProps {
  suggestions?: string[];
  onSend?: (payload: PromptPayload, signal: AbortSignal) => Promise<void>;
  disabled?: boolean;
  maxAttachments?: number;
  maxAttachmentSize?: number;
}
export function AIPromptComposer({
  suggestions = [
    "Explain this simply",
    "Help me find a direction",
    "Review my draft",
  ],
  onSend,
  disabled = false,
  maxAttachments = 4,
  maxAttachmentSize = 10 * 1024 * 1024,
}: AIPromptComposerProps) {
  const [text, setText] = useState("");
  const [files, setFiles] = useState<File[]>([]);
  const [status, setStatus] = useState("");
  const [pending, setPending] = useState(false);
  const controller = useRef<AbortController | null>(null);
  const id = useId();
  useEffect(
    () => () => {
      controller.current?.abort();
      controller.current = null;
    },
    [],
  );
  async function send() {
    if (disabled || controller.current || !text.trim() || !onSend) return;
    const request = new AbortController();
    controller.current = request;
    setPending(true);
    setStatus("Sending…");
    try {
      await onSend({ text: text.trim(), attachments: files }, request.signal);
      if (!request.signal.aborted) {
        setText("");
        setFiles([]);
        setStatus("Prompt sent.");
      }
    } catch {
      if (!request.signal.aborted)
        setStatus("Sending failed. Your draft is saved; try again.");
    } finally {
      if (controller.current === request) {
        controller.current = null;
        setPending(false);
      }
    }
  }
  function cancel() {
    controller.current?.abort();
    controller.current = null;
    setPending(false);
    setStatus("Sending cancelled. Your draft is saved.");
  }
  return (
    <form
      className="kittu-control kittu-surface kittu-stack"
      aria-label="AI prompt composer"
      aria-busy={pending}
      onSubmit={(e) => {
        e.preventDefault();
        void send();
      }}
    >
      <label htmlFor={id}>What are you thinking?</label>
      <textarea
        id={id}
        rows={4}
        maxLength={8000}
        value={text}
        disabled={disabled || pending}
        onChange={(e) => setText(e.target.value)}
        onKeyDown={(e) => {
          if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
            e.preventDefault();
            void send();
          }
        }}
        placeholder="Start with a small idea…"
      />
      <div className="kittu-row" aria-label="Prompt suggestions">
        {suggestions.map((s) => (
          <button
            key={s}
            type="button"
            disabled={disabled || pending}
            onClick={() => setText(s)}
          >
            {s}
          </button>
        ))}
      </div>
      <label htmlFor={`${id}-files`}>
        Attachments · up to {maxAttachments}
      </label>
      <input
        id={`${id}-files`}
        type="file"
        multiple
        disabled={disabled || pending}
        onChange={(e) => {
          const incoming = Array.from(e.target.files ?? []);
          if (
            files.length + incoming.length > maxAttachments ||
            incoming.some((f) => f.size > maxAttachmentSize)
          ) {
            setStatus(
              `Choose up to ${maxAttachments} attachments, each under ${Math.round(maxAttachmentSize / 1024 / 1024)} MB.`,
            );
          } else {
            setFiles((old) => [...old, ...incoming]);
            setStatus("Attachments added.");
          }
          e.target.value = "";
        }}
      />
      <ul className="kittu-list">
        {files.map((file, index) => (
          <li key={`${file.name}-${index}`} className="kittu-row">
            <span style={{ overflowWrap: "anywhere" }}>{file.name}</span>
            <button
              type="button"
              disabled={disabled || pending}
              onClick={() =>
                setFiles((old) => old.filter((_, i) => i !== index))
              }
            >
              Remove <span className="sr-only">{file.name}</span>
            </button>
          </li>
        ))}
      </ul>
      <div className="kittu-row">
        <span className="kittu-muted">
          {text.length}/8000 · ⌘ / Ctrl Enter to send
        </span>
        <button
          type="submit"
          disabled={disabled || pending || !text.trim() || !onSend}
        >
          {pending ? "Sending…" : "Send prompt ↗"}
        </button>
        {pending && (
          <button type="button" onClick={cancel}>
            Cancel
          </button>
        )}
      </div>
      <p role="status" className="kittu-status">
        {status ||
          (!onSend
            ? "Connect an onSend handler to send prompts."
            : "Your draft stays here until sending succeeds.")}
      </p>
    </form>
  );
}
