// packages/angular/src/elastic-sheet.component.ts
import {
  Component,
  ElementRef,
  computed,
  input,
  output,
  signal,
  viewChild,
} from "@angular/core";

@Component({
  selector: "kit-elastic-sheet",
  standalone: true,
  template: ` <div class="kit-control">
    <button type="button" [disabled]="disabled()" (click)="open()">
      Open elastic sheet ↗
    </button>
    <dialog
      #dialog
      class="kit-dialog kit-sheet kit-control"
      [style.height]="height() + 'dvh'"
      aria-label="Elastic sheet"
      (close)="origin = null"
    >
      <div class="kit-stack">
        <button
          type="button"
          class="kit-sheet-handle"
          aria-label="Resize sheet. Use arrow keys to change snap position"
          (keydown)="resizeKey($event)"
          (pointerdown)="start($event)"
          (pointermove)="drag($event)"
          (pointerup)="settle()"
          (pointercancel)="settle()"
        >
          Drag to resize
        </button>
        <div class="kit-row" style="justify-content:space-between">
          <h3>{{ title() }}</h3>
          <button type="button" (click)="close()">Close</button>
        </div>
        <div class="kit-row" aria-label="Sheet size">
          @for (position of positions(); track position) {
            <button
              type="button"
              [attr.aria-pressed]="height() === position"
              (click)="snap(position)"
            >
              {{ position }}%
            </button>
          }
        </div>
        <ng-content
          ><p class="kit-muted">
            Drag the handle, use its arrow keys, or choose a snap position.
            Escape closes the sheet.
          </p></ng-content
        >
      </div>
    </dialog>
  </div>`,
  host: { style: "display:block" },
})
export class KitElasticSheetComponent {
  readonly title = input("Make room for the details");
  readonly disabled = input(false);
  readonly snapPositions = input<number[]>([35, 65, 90]);
  readonly snapChange = output<number>();
  readonly positions = computed(() => {
    const values = [
      ...new Set(
        this.snapPositions().filter(
          (n) => Number.isFinite(n) && n >= 20 && n <= 95,
        ),
      ),
    ].sort((a, b) => a - b);
    return values.length ? values : [35, 65, 90];
  });
  readonly height = signal(35);
  readonly dialog = viewChild.required<ElementRef<HTMLDialogElement>>("dialog");
  origin: { y: number; height: number } | null = null;
  open(): void {
    this.snap(this.positions()[0]);
    this.dialog().nativeElement.showModal();
  }
  close(): void {
    this.dialog().nativeElement.close();
    this.origin = null;
  }
  snap(value: number): void {
    const next = this.positions().reduce((a, b) =>
      Math.abs(b - value) < Math.abs(a - value) ? b : a,
    );
    this.height.set(next);
    this.snapChange.emit(next);
  }
  start(event: PointerEvent): void {
    if (event.button !== 0) return;
    this.origin = { y: event.clientY, height: this.height() };
    (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);
  }
  drag(event: PointerEvent): void {
    if (this.origin)
      this.height.set(
        Math.max(
          this.positions()[0],
          Math.min(
            this.positions().at(-1)!,
            this.origin.height +
              ((this.origin.y - event.clientY) / window.innerHeight) * 100,
          ),
        ),
      );
  }
  settle(): void {
    this.origin = null;
    this.snap(this.height());
  }
  resizeKey(event: KeyboardEvent): void {
    const positions = this.positions();
    const index = positions.indexOf(this.height());
    if (!["ArrowUp", "ArrowDown", "Home", "End"].includes(event.key)) return;
    event.preventDefault();
    this.snap(
      event.key === "Home"
        ? positions[0]
        : event.key === "End"
          ? positions.at(-1)!
          : positions[
              Math.max(
                0,
                Math.min(
                  positions.length - 1,
                  index + (event.key === "ArrowUp" ? 1 : -1),
                ),
              )
            ],
    );
  }
}

// src/components/ui/ElasticSheet.tsx
import { useEffect, useId, useRef, useState } from "react";
import type { ReactNode } from "react";
import "../../lib/kit-controls.css";
export interface ElasticSheetProps {
  title?: string;
  children?: ReactNode;
  snapPositions?: number[];
  disabled?: boolean;
  onSnapChange?: (position: number) => void;
}
export function ElasticSheet({
  title = "Make room for the details",
  children,
  snapPositions = [35, 65, 90],
  disabled = false,
  onSnapChange,
}: ElasticSheetProps) {
  const snaps = [
    ...new Set(
      snapPositions.filter((n) => Number.isFinite(n) && n >= 20 && n <= 95),
    ),
  ].sort((a, b) => a - b);
  if (!snaps.length) snaps.push(35, 65, 90);
  const [height, setHeight] = useState(snaps[0]);
  const [open, setOpen] = useState(false);
  const dialog = useRef<HTMLDialogElement>(null);
  const origin = useRef<{ y: number; height: number } | null>(null);
  const titleId = useId();
  useEffect(() => {
    if (open) dialog.current?.showModal();
    else dialog.current?.close();
  }, [open]);
  const snap = (value: number) => {
    const next = snaps.reduce((a, b) =>
      Math.abs(b - value) < Math.abs(a - value) ? b : a,
    );
    setHeight(next);
    onSnapChange?.(next);
  };
  return (
    <div className="kit-control">
      <button type="button" disabled={disabled} onClick={() => setOpen(true)}>
        Open elastic sheet ↗
      </button>
      <dialog
        ref={dialog}
        className="kit-dialog kit-sheet kit-control"
        style={{ height: `${height}dvh` }}
        aria-labelledby={titleId}
        onClose={() => {
          setOpen(false);
          origin.current = null;
        }}
      >
        <div className="kit-stack">
          <button
            type="button"
            className="kit-sheet-handle"
            aria-label="Resize sheet. Use arrow keys to change snap position"
            onKeyDown={(e) => {
              if (["ArrowUp", "ArrowDown", "Home", "End"].includes(e.key)) {
                e.preventDefault();
                const index = snaps.indexOf(height);
                snap(
                  e.key === "Home"
                    ? snaps[0]
                    : e.key === "End"
                      ? snaps.at(-1)!
                      : snaps[
                          Math.max(
                            0,
                            Math.min(
                              snaps.length - 1,
                              index + (e.key === "ArrowUp" ? 1 : -1),
                            ),
                          )
                        ],
                );
              }
            }}
            onPointerDown={(e) => {
              origin.current = { y: e.clientY, height };
              e.currentTarget.setPointerCapture(e.pointerId);
            }}
            onPointerMove={(e) => {
              if (origin.current)
                setHeight(
                  Math.max(
                    snaps[0],
                    Math.min(
                      snaps.at(-1)!,
                      origin.current.height +
                        ((origin.current.y - e.clientY) / window.innerHeight) *
                          100,
                    ),
                  ),
                );
            }}
            onPointerUp={() => {
              origin.current = null;
              snap(height);
            }}
            onPointerCancel={() => {
              origin.current = null;
              snap(height);
            }}
          >
            Drag to resize
          </button>
          <div
            className="kit-row"
            style={{ justifyContent: "space-between" }}
          >
            <h3 id={titleId}>{title}</h3>
            <button type="button" onClick={() => setOpen(false)}>
              Close
            </button>
          </div>
          <div className="kit-row" aria-label="Sheet size">
            {snaps.map((n) => (
              <button
                type="button"
                key={n}
                aria-pressed={height === n}
                onClick={() => snap(n)}
              >
                {n}%
              </button>
            ))}
          </div>
          {children ?? (
            <p className="kit-muted">
              A little space to think. Drag the handle, use its arrow keys, or
              choose a snap position. Escape closes the sheet.
            </p>
          )}
        </div>
      </dialog>
    </div>
  );
}
