// packages/angular/src/hold-to-confirm.component.ts
import {
  Component,
  DestroyRef,
  effect,
  inject,
  input,
  output,
  signal,
} from "@angular/core";

@Component({
  selector: "kittu-hold-to-confirm",
  standalone: true,
  host: { style: "display:block" },
  template: ` <div class="kittu-control kittu-stack">
    <button
      type="button"
      class="kittu-hold"
      [disabled]="disabled() || state() === 'pending' || state() === 'success'"
      (pointerdown)="pointerStart($event)"
      (pointerup)="cancel()"
      (pointercancel)="cancel()"
      (lostpointercapture)="cancel()"
      (blur)="cancel()"
      (keydown)="keyDown($event)"
      (keyup)="keyUp($event)"
    >
      <span
        class="kittu-hold-fill"
        [style.transform]="'scaleX(' + progress() + ')'"
      ></span
      >{{
        state() === "pending"
          ? "Confirming…"
          : state() === "success"
            ? "Confirmed ✓"
            : label()
      }}
    </button>
    <progress
      aria-label="Confirmation hold progress"
      max="1"
      [value]="progress()"
    ></progress>
    <p class="kittu-status" role="status">
      {{
        state() === "error"
          ? "Confirmation failed. Hold again to retry."
          : state() === "success"
            ? "Action completed."
            : state() === "pending"
              ? "Waiting for confirmation…"
              : "Hold with a pointer, Space, or Enter. Release early to cancel."
      }}
    </p>
    @if (state() === "success") {
      <button type="button" (click)="reset()">Reset</button>
    }
  </div>`,
})
export class KittuHoldToConfirmComponent {
  readonly label = input("Hold to confirm");
  readonly duration = input(1200);
  readonly disabled = input(false);
  readonly confirm = input<() => void | Promise<void>>();
  readonly confirmed = output<void>();
  readonly progress = signal(0);
  readonly state = signal<"idle" | "holding" | "pending" | "success" | "error">(
    "idle",
  );
  private timer: ReturnType<typeof setInterval> | undefined;
  private destroyed = false;
  constructor() {
    inject(DestroyRef).onDestroy(() => {
      this.destroyed = true;
      this.stop();
    });
    effect(() => {
      if (this.disabled()) this.cancel();
    });
  }
  private stop(): void {
    if (this.timer) clearInterval(this.timer);
    this.timer = undefined;
  }
  cancel(): void {
    if (this.state() !== "holding") return;
    this.stop();
    this.progress.set(0);
    this.state.set("idle");
  }
  reset(): void {
    this.progress.set(0);
    this.state.set("idle");
  }
  start(): void {
    if (
      this.disabled() ||
      ["holding", "pending", "success"].includes(this.state())
    )
      return;
    this.progress.set(0);
    this.state.set("holding");
    const started = Date.now();
    this.timer = setInterval(() => {
      const next = Math.min(
        1,
        (Date.now() - started) / Math.max(250, this.duration()),
      );
      this.progress.set(next);
      if (next === 1) {
        this.stop();
        void this.finish();
      }
    }, 16);
  }
  private async finish(): Promise<void> {
    this.state.set("pending");
    try {
      await this.confirm()?.();
      if (!this.destroyed) {
        this.state.set("success");
        this.confirmed.emit();
      }
    } catch {
      if (!this.destroyed) {
        this.state.set("error");
        this.progress.set(0);
      }
    }
  }
  pointerStart(event: PointerEvent): void {
    if (event.button !== 0) return;
    (event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);
    this.start();
  }
  keyDown(event: KeyboardEvent): void {
    if (event.key === " " || event.key === "Enter") {
      event.preventDefault();
      if (!event.repeat) this.start();
    }
    if (event.key === "Escape") this.cancel();
  }
  keyUp(event: KeyboardEvent): void {
    if (event.key === " " || event.key === "Enter") {
      event.preventDefault();
      this.cancel();
    }
  }
}

// src/components/ui/HoldToConfirm.tsx
import { useEffect, useRef, useState } from "react";
import "../../lib/kittu-controls.css";
export interface HoldToConfirmProps {
  label?: string;
  duration?: number;
  disabled?: boolean;
  onConfirm?: () => void | Promise<void>;
}
export function HoldToConfirm({
  label = "Hold to confirm",
  duration = 1200,
  disabled = false,
  onConfirm,
}: HoldToConfirmProps) {
  const [progress, setProgress] = useState(0);
  const [status, setStatus] = useState<
    "idle" | "holding" | "pending" | "success" | "error"
  >("idle");
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);
  const running = useRef(false);
  const mounted = useRef(true);
  const stop = () => {
    if (timer.current) clearInterval(timer.current);
    timer.current = null;
    running.current = false;
  };
  useEffect(() => {
    mounted.current = true;
    return () => {
      mounted.current = false;
      stop();
    };
  }, []);
  useEffect(() => {
    if (disabled) {
      stop();
      setProgress(0);
      setStatus((s) => (s === "holding" ? "idle" : s));
    }
  }, [disabled]);
  const cancel = () => {
    if (running.current) {
      stop();
      setProgress(0);
      setStatus("idle");
    }
  };
  const start = () => {
    if (
      disabled ||
      running.current ||
      status === "pending" ||
      status === "success"
    )
      return;
    running.current = true;
    setStatus("holding");
    setProgress(0);
    const startTime = Date.now();
    timer.current = setInterval(() => {
      const value = Math.min(
        1,
        (Date.now() - startTime) / Math.max(250, duration),
      );
      setProgress(value);
      if (value === 1) {
        stop();
        setStatus("pending");
        Promise.resolve()
          .then(() => onConfirm?.())
          .then(
            () => {
              if (mounted.current) setStatus("success");
            },
            () => {
              if (mounted.current) {
                setStatus("error");
                setProgress(0);
              }
            },
          );
      }
    }, 16);
  };
  return (
    <div className="kittu-control kittu-stack">
      <button
        type="button"
        className="kittu-hold"
        disabled={disabled || status === "pending" || status === "success"}
        onPointerDown={(e) => {
          if (e.button !== 0) return;
          e.currentTarget.setPointerCapture(e.pointerId);
          start();
        }}
        onPointerUp={cancel}
        onPointerCancel={cancel}
        onLostPointerCapture={cancel}
        onBlur={cancel}
        onKeyDown={(e) => {
          if (e.key === " " || e.key === "Enter") {
            e.preventDefault();
            if (!e.repeat) start();
          }
          if (e.key === "Escape") cancel();
        }}
        onKeyUp={(e) => {
          if (e.key === " " || e.key === "Enter") {
            e.preventDefault();
            cancel();
          }
        }}
      >
        <span
          className="kittu-hold-fill"
          style={{ transform: `scaleX(${progress})` }}
        />
        {status === "pending"
          ? "Confirming…"
          : status === "success"
            ? "Confirmed ✓"
            : label}
      </button>
      <progress
        aria-label="Confirmation hold progress"
        max={1}
        value={progress}
      />
      <p className="kittu-status" role="status">
        {status === "error"
          ? "Confirmation failed. Hold again to retry."
          : status === "success"
            ? "Action completed."
            : status === "pending"
              ? "Waiting for confirmation…"
              : "Hold with a pointer, Space, or Enter. Release early to cancel."}
      </p>
      {status === "success" && (
        <button
          type="button"
          onClick={() => {
            setStatus("idle");
            setProgress(0);
          }}
        >
          Reset
        </button>
      )}
    </div>
  );
}
