// packages/angular/src/interactive-data-card.component.ts
import { Component, DestroyRef, inject, input, signal } from "@angular/core";

@Component({
  selector: "kittu-interactive-data-card",
  standalone: true,
  host: { style: "display:block" },
  template: ` <article
    class="kittu-control kittu-surface kittu-stack"
    [attr.aria-busy]="loading() || pending()"
  >
    <h3>{{ title() }}</h3>
    <p>{{ loading() ? "Loading summary…" : summary() }}</p>
    @if (error()) {
      <p role="alert">{{ error() }}</p>
    }
    <button
      type="button"
      [disabled]="disabled() || loading()"
      [attr.aria-expanded]="expanded()"
      (click)="expanded.set(!expanded())"
    >
      {{ expanded() ? "Less detail −" : "Explore details +" }}
    </button>
    <div [hidden]="!expanded()" class="kittu-stack">
      <ng-content
        ><p class="kittu-muted">
          Your team shipped 8 features and resolved 16 issues. Keep the next
          step small and intentional.
        </p></ng-content
      ><button
        type="button"
        [disabled]="disabled() || loading() || pending()"
        (click)="act()"
      >
        {{ pending() ? "Updating…" : actionLabel() }}
      </button>
    </div>
    <p role="status" class="kittu-status">{{ status() }}</p>
  </article>`,
})
export class KittuInteractiveDataCardComponent {
  readonly title = input("Weekly momentum");
  readonly summary = input("24 tasks completed · 12% ahead");
  readonly loading = input(false);
  readonly error = input("");
  readonly disabled = input(false);
  readonly actionLabel = input("Refresh report");
  readonly action = input<() => void | Promise<void>>();
  readonly expanded = signal(false);
  readonly pending = signal(false);
  readonly status = signal("");
  private destroyed = false;
  constructor() {
    inject(DestroyRef).onDestroy(() => {
      this.destroyed = true;
    });
  }
  async act(): Promise<void> {
    if (this.pending() || this.disabled() || this.loading()) return;
    this.pending.set(true);
    this.status.set("Updating report…");
    try {
      await this.action()?.();
      if (!this.destroyed) this.status.set("Report updated.");
    } catch {
      if (!this.destroyed) this.status.set("Unable to update. Try again.");
    } finally {
      if (!this.destroyed) this.pending.set(false);
    }
  }
}

// src/components/ui/InteractiveDataCard.tsx
import { useId, useState } from "react";
import type { ReactNode } from "react";
import "../../lib/kittu-controls.css";
export interface InteractiveDataCardProps {
  title?: string;
  summary?: ReactNode;
  children?: ReactNode;
  actionLabel?: string;
  onAction?: () => void | Promise<void>;
  loading?: boolean;
  error?: string;
  disabled?: boolean;
}
export function InteractiveDataCard({
  title = "Weekly momentum",
  summary = "24 tasks completed · 12% ahead",
  children,
  actionLabel = "Refresh report",
  onAction,
  loading = false,
  error,
  disabled = false,
}: InteractiveDataCardProps) {
  const [expanded, setExpanded] = useState(false);
  const [state, setState] = useState("");
  const id = useId();
  async function act() {
    setState("pending");
    try {
      await onAction?.();
      setState("Report updated.");
    } catch {
      setState("Unable to update. Try again.");
    }
  }
  return (
    <article
      className="kittu-control kittu-surface kittu-stack"
      aria-busy={loading || state === "pending"}
    >
      <h3>{title}</h3>
      <div>{loading ? "Loading summary…" : summary}</div>
      {error && <p role="alert">{error}</p>}
      <button
        type="button"
        disabled={disabled || loading}
        aria-expanded={expanded}
        aria-controls={id}
        onClick={() => setExpanded(!expanded)}
      >
        {expanded ? "Less detail −" : "Explore details +"}
      </button>
      <div id={id} hidden={!expanded} className="kittu-stack">
        {children ?? (
          <p className="kittu-muted">
            Your team shipped 8 features and resolved 16 issues. Keep the next
            step small and intentional.
          </p>
        )}
        <button
          type="button"
          disabled={disabled || loading || state === "pending"}
          onClick={act}
        >
          {state === "pending" ? "Updating…" : actionLabel}
        </button>
      </div>
      <p className="kittu-status" role="status">
        {state === "pending" ? "Updating report…" : state}
      </p>
    </article>
  );
}
