// packages/angular/src/liquid-command-palette.component.ts
import {
  Component,
  DestroyRef,
  ElementRef,
  HostListener,
  computed,
  inject,
  input,
  signal,
  viewChild,
} from "@angular/core";
import type { LiquidCommand } from "./types";

@Component({
  selector: "kittu-liquid-command-palette",
  standalone: true,
  host: { style: "display:block" },
  template: ` <div class="kittu-control">
    <button type="button" [disabled]="disabled()" (click)="open()">
      Find a command <kbd>⌘ / Ctrl K</kbd>
    </button>
    <dialog
      #dialog
      class="kittu-dialog kittu-control"
      aria-label="Command palette"
    >
      <div class="kittu-stack">
        <div class="kittu-row">
          <h3>Where next?</h3>
          <button type="button" (click)="close()">Close</button>
        </div>
        <input
          #search
          role="combobox"
          aria-label="Search commands"
          aria-autocomplete="list"
          aria-expanded="true"
          [attr.aria-controls]="listId"
          [attr.aria-activedescendant]="
            current() ? listId + '-' + current()!.id : null
          "
          [value]="query()"
          (input)="filter($event)"
          (keydown)="navigate($event)"
          placeholder="Search commands…"
        />
        <ul
          [id]="listId"
          role="listbox"
          aria-label="Commands"
          class="kittu-list"
          style="max-height:45dvh;overflow:auto"
        >
          @for (command of results(); track command.id) {
            <li
              role="option"
              [id]="listId + '-' + command.id"
              [attr.aria-selected]="current()?.id === command.id"
              [attr.aria-disabled]="command.disabled || false"
              (mousedown)="$event.preventDefault()"
              (click)="run(command)"
              [style.opacity]="command.disabled ? 0.5 : 1"
              style="padding:.75rem;border-radius:.75rem;cursor:pointer"
            >
              {{ command.label }}
            </li>
          }
        </ul>
        @if (!results().length) {
          <p>No matching commands.</p>
        }
        <p role="status" class="kittu-status">{{ status() }}</p>
      </div>
    </dialog>
  </div>`,
})
export class KittuLiquidCommandPaletteComponent {
  readonly commands = input<LiquidCommand[]>([]);
  readonly disabled = input(false);
  readonly query = signal("");
  readonly active = signal(0);
  readonly status = signal("");
  readonly busy = signal(false);
  readonly dialog = viewChild.required<ElementRef<HTMLDialogElement>>("dialog");
  readonly search = viewChild.required<ElementRef<HTMLInputElement>>("search");
  readonly listId =
    "kittu-commands-" +
    inject(ElementRef).nativeElement.tagName.toLowerCase() +
    "-" +
    nextId++;
  readonly results = computed(() =>
    this.commands().filter((c) =>
      `${c.label} ${c.keywords ?? ""}`
        .toLowerCase()
        .includes(this.query().toLowerCase()),
    ),
  );
  readonly selectable = computed(() =>
    this.results().filter((c) => !c.disabled),
  );
  readonly current = computed(
    () =>
      this.selectable()[
        Math.min(this.active(), Math.max(0, this.selectable().length - 1))
      ],
  );
  private destroyed = false;
  constructor() {
    inject(DestroyRef).onDestroy(() => {
      this.destroyed = true;
    });
  }
  open(): void {
    if (this.disabled()) return;
    this.dialog().nativeElement.showModal();
    this.search().nativeElement.focus();
  }
  close(): void {
    this.dialog().nativeElement.close();
  }
  @HostListener("window:keydown", ["$event"]) shortcut(
    event: KeyboardEvent,
  ): void {
    if (event.defaultPrevented || this.disabled()) return;
    if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") {
      event.preventDefault();
      if (this.dialog().nativeElement.open) {
        this.close();
      } else {
        this.open();
      }
    }
  }
  filter(event: Event): void {
    this.query.set((event.target as HTMLInputElement).value);
    this.active.set(0);
  }
  navigate(event: KeyboardEvent): void {
    const count = Math.max(1, this.selectable().length);
    if (["ArrowDown", "ArrowUp", "Home", "End"].includes(event.key)) {
      event.preventDefault();
      this.active.set(
        event.key === "Home"
          ? 0
          : event.key === "End"
            ? count - 1
            : (this.active() + (event.key === "ArrowDown" ? 1 : -1) + count) %
              count,
      );
      const id = this.current()?.id;
      if (id)
        this.dialog()
          .nativeElement.querySelector(
            `[id="${this.listId}-${CSS.escape(id)}"]`,
          )
          ?.scrollIntoView({ block: "nearest" });
    }
    if (event.key === "Enter" && this.current()) {
      event.preventDefault();
      void this.run(this.current()!);
    }
  }
  async run(command: LiquidCommand): Promise<void> {
    if (command.disabled || this.busy()) return;
    this.busy.set(true);
    this.status.set("Running command…");
    try {
      await command.onSelect();
      if (!this.destroyed) {
        this.status.set("Command completed.");
        this.close();
      }
    } catch {
      if (!this.destroyed) this.status.set("Command failed. Try again.");
    } finally {
      if (!this.destroyed) this.busy.set(false);
    }
  }
}
let nextId = 0;

// src/components/ui/LiquidCommandPalette.tsx
import { useEffect, useId, useRef, useState } from "react";
import "../../lib/kittu-controls.css";
export interface LiquidCommand {
  id: string;
  label: string;
  keywords?: string;
  disabled?: boolean;
  onSelect: () => void | Promise<void>;
}
export interface LiquidCommandPaletteProps {
  commands?: LiquidCommand[];
  disabled?: boolean;
}
const sample: LiquidCommand[] = [
  {
    id: "home",
    label: "Go to home",
    onSelect: () => {
      window.location.assign("/");
    },
  },
  {
    id: "components",
    label: "Browse components",
    keywords: "library catalog",
    onSelect: () => {
      window.location.assign("/components");
    },
  },
  {
    id: "docs",
    label: "Read the documentation",
    onSelect: () => {
      window.location.assign("/docs/introduction");
    },
  },
];
export function LiquidCommandPalette({
  commands = sample,
  disabled = false,
}: LiquidCommandPaletteProps) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [active, setActive] = useState(0);
  const [status, setStatus] = useState("");
  const dialog = useRef<HTMLDialogElement>(null);
  const input = useRef<HTMLInputElement>(null);
  const busy = useRef(false);
  const id = useId();
  const results = commands.filter((c) =>
    `${c.label} ${c.keywords ?? ""}`
      .toLowerCase()
      .includes(query.toLowerCase()),
  );
  const selectable = results.filter((c) => !c.disabled);
  const current =
    selectable[Math.min(active, Math.max(0, selectable.length - 1))];
  useEffect(() => {
    if (open) {
      dialog.current?.showModal();
      input.current?.focus();
    } else dialog.current?.close();
  }, [open]);
  useEffect(() => {
    const key = (e: KeyboardEvent) => {
      if (e.defaultPrevented) return;
      if (
        (e.metaKey || e.ctrlKey) &&
        e.key.toLowerCase() === "k" &&
        !disabled
      ) {
        e.preventDefault();
        setOpen((o) => !o);
      }
    };
    window.addEventListener("keydown", key, true);
    return () => window.removeEventListener("keydown", key, true);
  }, [disabled]);
  useEffect(() => {
    if (open && current) document.getElementById(`${id}-${current.id}`)?.scrollIntoView?.({ block: 'nearest' });
  }, [open, current, id]);
  async function run(command: LiquidCommand) {
    if (command.disabled || busy.current) return;
    busy.current = true;
    setStatus("Running command…");
    try {
      await command.onSelect();
      setStatus("Command completed.");
      setOpen(false);
    } catch {
      setStatus("Command failed. Try again.");
    } finally {
      busy.current = false;
    }
  }
  return (
    <div className="kittu-control">
      <button type="button" disabled={disabled} onClick={() => setOpen(true)}>
        Find a command <kbd>⌘ / Ctrl K</kbd>
      </button>
      <dialog
        ref={dialog}
        className="kittu-dialog kittu-control"
        aria-label="Command palette"
        onClose={() => setOpen(false)}
      >
        <div className="kittu-stack">
          <div className="kittu-row">
            <h3>Where next?</h3>
            <button type="button" onClick={() => setOpen(false)}>
              Close
            </button>
          </div>
          <input
            ref={input}
            role="combobox"
            aria-label="Search commands"
            aria-expanded="true"
            aria-autocomplete="list"
            aria-controls={`${id}-list`}
            aria-activedescendant={current ? `${id}-${current.id}` : undefined}
            value={query}
            onChange={(e) => {
              setQuery(e.target.value);
              setActive(0);
            }}
            onKeyDown={(e) => {
              if (e.key === "ArrowDown" || e.key === "ArrowUp") {
                e.preventDefault();
                setActive(
                  (i) =>
                    (i +
                      (e.key === "ArrowDown" ? 1 : -1) +
                      Math.max(1, selectable.length)) %
                    Math.max(1, selectable.length),
                );
              }
              if (e.key === "Home") {
                e.preventDefault();
                setActive(0);
              }
              if (e.key === "End") {
                e.preventDefault();
                setActive(Math.max(0, selectable.length - 1));
              }
              if (e.key === "Enter" && current) {
                e.preventDefault();
                void run(current);
              }
            }}
            placeholder="Search commands…"
          />
          <ul
            id={`${id}-list`}
            role="listbox"
            aria-label="Commands"
            className="kittu-list"
            style={{ maxHeight: "45dvh", overflow: "auto" }}
          >
            {results.map((c) => (
              <li
                role="option"
                id={`${id}-${c.id}`}
                key={c.id}
                aria-selected={current?.id === c.id}
                aria-disabled={c.disabled}
                onMouseDown={(e) => e.preventDefault()}
                onClick={() => void run(c)}
                style={{
                  padding: ".75rem",
                  borderRadius: ".75rem",
                  cursor: c.disabled ? "not-allowed" : "pointer",
                  opacity: c.disabled ? 0.5 : 1,
                  background: current?.id === c.id ? "#8883" : undefined,
                }}
              >
                {c.label}
              </li>
            ))}
          </ul>
          {!results.length && <p>No matching commands.</p>}
          <p role="status" className="kittu-status">
            {status}
          </p>
        </div>
      </dialog>
    </div>
  );
}
