// packages/angular/src/orbital-loading-ring.component.ts
// Generated from authored native templates in scripts/generate-angular-ports.ts.
import { Component, computed, input } from '@angular/core';
import {ViewEncapsulation} from '@angular/core';
import type {OrbitalLoadingRingVariant} from './orbital-loading-ring-types';
@Component({
 selector:"kittu-orbital-loading-ring", standalone:true,
 host:{'data-kittu':'orbital-loading-ring','role':'status','[attr.aria-label]':'accessibleLabel()','[style.width.px]':'size()','[style.height.px]':'size()','[class]':'"k-orbital-parity "+className()'},
 encapsulation:ViewEncapsulation.None,styleUrls:["./orbital-loading-ring.css"],
template:`
<span class="k-orbital-label">{{label()}}</span>
<svg class="k-orbital-tracks" viewBox="0 0 100 100" fill="none" aria-hidden="true">
<circle cx="50" cy="50" r="44" stroke="#282828" stroke-width="1.5" stroke-dasharray="3 3"/>
<circle cx="50" cy="50" r="30" stroke="#333333" stroke-width="1.5"/>
</svg>
<div class="k-orbital-outer" [style.animation]="outerAnimation()">
<span class="k-orbital-satellite-outer">
</span>@if(variant()!=='minimal'){<span class="k-orbital-satellite-bottom">
</span>}</div>
<div class="k-orbital-inner" [style.animation]="innerAnimation()">
<span class="k-orbital-satellite-inner">
</span>@if(variant()==='dense'){<span class="k-orbital-satellite-right">
</span>}</div>
<div class="k-orbital-core" [style.animation]="coreAnimation()">
</div>
`
})
export class KittuOrbitalLoadingRingComponent {
private readonly defaultAriaLabel=Symbol('default aria-label');readonly size=input<number,number|undefined>(72,{transform:value=>value===undefined?72:value});readonly speed=input<number,number|undefined>(1,{transform:value=>value===undefined?1:value});readonly variant=input<OrbitalLoadingRingVariant,OrbitalLoadingRingVariant|undefined>('default',{transform:value=>value===undefined?'default':value});readonly label=input<string,string|undefined>('Loading',{transform:value=>value===undefined?'Loading':value});readonly className=input<string,string|undefined>('',{transform:value=>value===undefined?'':value});readonly ariaLabel=input<string|symbol|undefined,string|undefined>(this.defaultAriaLabel,{alias:'aria-label',transform:value=>value});readonly accessibleLabel=computed(()=>{const value=this.ariaLabel();return typeof value==='symbol'?this.label():value;});readonly outerAnimation=computed(()=>'k-orbital-cw '+(2.4/this.speed())+'s linear infinite');readonly innerAnimation=computed(()=>'k-orbital-ccw '+(1.6/this.speed())+'s cubic-bezier(0.4, 0, 0.2, 1) infinite');readonly coreAnimation=computed(()=>'k-orbital-pulse '+(1.2/this.speed())+'s ease-in-out infinite');
}

// src/components/ui/OrbitalLoadingRing.tsx
import React from 'react';
import { cn } from '../../lib/utils';

export interface OrbitalLoadingRingProps extends React.HTMLAttributes<HTMLDivElement> {
  size?: number;
  speed?: number;
  variant?: 'default' | 'dense' | 'minimal';
  label?: string;
}

export const OrbitalLoadingRing: React.FC<OrbitalLoadingRingProps> = ({
  size = 72,
  speed = 1,
  variant = 'default',
  label = 'Loading',
  className,
  style,
  ...props
}) => {
  const durationOuter = `${2.4 / speed}s`;
  const durationInner = `${1.6 / speed}s`;
  const durationCenter = `${1.2 / speed}s`;

  return (
    <div
      role="status"
      aria-label={label}
      className={cn('relative inline-flex items-center justify-center text-[#FAFAFA] select-none', className)}
      style={{ width: size, height: size, ...style }}
      {...props}
    >
      <style>{`
        @keyframes kittu-ui-orbit-cw {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
        @keyframes kittu-ui-orbit-ccw {
          from { transform: rotate(360deg); }
          to { transform: rotate(0deg); }
        }
        @keyframes kittu-ui-orbit-glow-pulse {
          0%, 100% { opacity: 0.6; transform: scale(0.96); }
          50% { opacity: 1; transform: scale(1.04); }
        }
        @media (prefers-reduced-motion: reduce) {
          .kittu-ui-orbit-spin-cw,
          .kittu-ui-orbit-spin-ccw,
          .kittu-ui-orbit-core-pulse { animation: none !important; }
        }
      `}</style>
      <span className="sr-only">{label}</span>

      {/* Static Subdued Background Tracks */}
      <svg
        className="pointer-events-none absolute inset-0 h-full w-full"
        viewBox="0 0 100 100"
        fill="none"
        aria-hidden="true"
      >
        <circle cx="50" cy="50" r="44" stroke="#282828" strokeWidth="1.5" strokeDasharray="3 3" />
        <circle cx="50" cy="50" r="30" stroke="#333333" strokeWidth="1.5" />
      </svg>

      {/* Outer Orbit Track & Glowing Satellite */}
      <div
        className="kittu-ui-orbit-spin-cw pointer-events-none absolute inset-0 flex items-center justify-center"
        style={{ animation: `kittu-ui-orbit-cw ${durationOuter} linear infinite` }}
      >
        <span
          className="absolute -top-1 left-1/2 h-2.5 w-2.5 -translate-x-1/2 rounded-full bg-white shadow-[0_0_10px_2px_rgba(255,255,255,0.6)]"
        />
        {variant !== 'minimal' && (
          <span
            className="absolute -bottom-0.5 left-1/2 h-1.5 w-1.5 -translate-x-1/2 rounded-full bg-white/40"
          />
        )}
      </div>

      {/* Inner Counter-Rotating Orbit */}
      <div
        className="kittu-ui-orbit-spin-ccw pointer-events-none absolute inset-[18%] flex items-center justify-center"
        style={{ animation: `kittu-ui-orbit-ccw ${durationInner} cubic-bezier(0.4, 0, 0.2, 1) infinite` }}
      >
        <span
          className="absolute -top-1 left-1/2 h-2 w-2 -translate-x-1/2 rounded-full bg-zinc-300 shadow-[0_0_8px_rgba(255,255,255,0.4)]"
        />
        {variant === 'dense' && (
          <span
            className="absolute top-1/2 -right-1 h-1.5 w-1.5 -translate-y-1/2 rounded-full bg-zinc-400/50"
          />
        )}
      </div>

      {/* Central Pulsing Core */}
      <div
        className="kittu-ui-orbit-core-pulse h-3 w-3 rounded-full bg-white shadow-[0_0_12px_rgba(255,255,255,0.5)]"
        style={{ animation: `kittu-ui-orbit-glow-pulse ${durationCenter} ease-in-out infinite` }}
      />
    </div>
  );
};
